// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://envcoclhjitywvgwuywn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudmNvY2xoaml0eXd2Z3d1eXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDUyODgsImV4cCI6MjA2ODYyMTI4OH0.rx3tvpZzmNfNbo6KJFbw1mqEHp0jbUOvc0lhdlPJEQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});